"""词组词典数据

包含 200+ 常用词组及其拼音，覆盖日常生活、科技、社会、自然等领域。
数据格式: { "词组": ("拼音1", "拼音2", ...) }
"""

PHRASE_DICT: dict[str, tuple[str, ...]] = {
    "中国": ("zhong", "guo"),
    "中华": ("zhong", "hua"),
    "人民": ("ren", "min"),
    "共和国": ("gong", "he", "guo"),
    "中华人民共和国": ("zhong", "hua", "ren", "min", "gong", "he", "guo"),
    "你好": ("ni", "hao"),
    "世界": ("shi", "jie"),
    "你好世界": ("ni", "hao", "shi", "jie"),
    "大家": ("da", "jia"),
    "你好大家": ("ni", "hao", "da", "jia"),
    "我们": ("wo", "men"),
    "你们": ("ni", "men"),
    "他们": ("ta", "men"),
    "今天": ("jin", "tian"),
    "明天": ("ming", "tian"),
    "昨天": ("zuo", "tian"),
    "天气": ("tian", "qi"),
    "好天气": ("hao", "tian", "qi"),
    "学习": ("xue", "xi"),
    "学校": ("xue", "xiao"),
    "学生": ("xue", "sheng"),
    "老师": ("lao", "shi"),
    "同学": ("tong", "xue"),
    "工作": ("gong", "zuo"),
    "公司": ("gong", "si"),
    "上班": ("shang", "ban"),
    "下班": ("xia", "ban"),
    "办公室": ("ban", "gong", "shi"),
    "电脑": ("dian", "nao"),
    "手机": ("shou", "ji"),
    "电话": ("dian", "hua"),
    "互联网": ("hu", "lian", "wang"),
    "网络": ("wang", "luo"),
    "网站": ("wang", "zhan"),
    "邮件": ("you", "jian"),
    "邮箱": ("you", "xiang"),
    "朋友": ("peng", "you"),
    "家人": ("jia", "ren"),
    "父亲": ("fu", "qin"),
    "母亲": ("mu", "qin"),
    "兄弟": ("xiong", "di"),
    "姐妹": ("jie", "mei"),
    "爱人": ("ai", "ren"),
    "孩子": ("hai", "zi"),
    "宝宝": ("bao", "bao"),
    "吃饭": ("chi", "fan"),
    "米饭": ("mi", "fan"),
    "面条": ("mian", "tiao"),
    "饺子": ("jiao", "zi"),
    "包子": ("bao", "zi"),
    "馒头": ("man", "tou"),
    "咖啡": ("ka", "fei"),
    "奶茶": ("nai", "cha"),
    "果汁": ("guo", "zhi"),
    "开车": ("kai", "che"),
    "汽车": ("qi", "che"),
    "火车": ("huo", "che"),
    "飞机": ("fei", "ji"),
    "地铁": ("di", "tie"),
    "公交": ("gong", "jiao"),
    "自行车": ("zi", "xing", "che"),
    "医院": ("yi", "yuan"),
    "医生": ("yi", "sheng"),
    "护士": ("hu", "shi"),
    "感冒": ("gan", "mao"),
    "发烧": ("fa", "shao"),
    "头疼": ("tou", "teng"),
    "牙疼": ("ya", "teng"),
    "看病": ("kan", "bing"),
    "吃药": ("chi", "yao"),
    "上学": ("shang", "xue"),
    "放学": ("fang", "xue"),
    "考试": ("kao", "shi"),
    "作业": ("zuo", "ye"),
    "成绩": ("cheng", "ji"),
    "大学": ("da", "xue"),
    "高中": ("gao", "zhong"),
    "初中": ("chu", "zhong"),
    "小学": ("xiao", "xue"),
    "班级": ("ban", "ji"),
    "课程": ("ke", "cheng"),
    "数学": ("shu", "xue"),
    "语文": ("yu", "wen"),
    "英语": ("ying", "yu"),
    "物理": ("wu", "li"),
    "化学": ("hua", "xue"),
    "生物": ("sheng", "wu"),
    "历史": ("li", "shi"),
    "地理": ("di", "li"),
    "政治": ("zheng", "zhi"),
    "体育": ("ti", "yu"),
    "音乐": ("yin", "yue"),
    "美术": ("mei", "shu"),
    "科技": ("ke", "ji"),
    "技术": ("ji", "shu"),
    "创新": ("chuang", "xin"),
    "发展": ("fa", "zhan"),
    "经济": ("jing", "ji"),
    "文化": ("wen", "hua"),
    "教育": ("jiao", "yu"),
    "医疗": ("yi", "liao"),
    "健康": ("jian", "kang"),
    "安全": ("an", "quan"),
    "国家": ("guo", "jia"),
    "民族": ("min", "zu"),
    "人民共和国": ("ren", "min", "gong", "he", "guo"),
    "人民政府": ("ren", "min", "zheng", "fu"),
    "中国人民": ("zhong", "guo", "ren", "min"),
    "中国共产党": ("zhong", "guo", "gong", "chan", "dang"),
    "社会主义": ("she", "hui", "zhu", "yi"),
    "现代化": ("xian", "dai", "hua"),
    "共产主义": ("gong", "chan", "zhu", "yi"),
    "资本主义": ("zi", "ben", "zhu", "yi"),
    "民主": ("min", "zhu"),
    "自由": ("zi", "you"),
    "平等": ("ping", "deng"),
    "博爱": ("bo", "ai"),
    "和平": ("he", "ping"),
    "团结": ("tuan", "jie"),
    "奋斗": ("fen", "dou"),
    "努力": ("nu", "li"),
    "坚持": ("jian", "chi"),
    "成功": ("cheng", "gong"),
    "失败": ("shi", "bai"),
    "进步": ("jin", "bu"),
    "改革": ("gai", "ge"),
    "开放": ("kai", "fang"),
    "改革开发": ("gai", "ge", "kai", "fang"),
    "保护环境": ("bao", "hu", "huan", "jing"),
    "绿色": ("lv", "se"),
    "环保": ("huan", "bao"),
    "节约用水": ("jie", "yue", "yong", "shui"),
    "气候变化": ("qi", "hou", "bian", "hua"),
    "全球变暖": ("quan", "qiu", "bian", "nuan"),
    "人工智能": ("ren", "gong", "zhi", "neng"),
    "机器学习": ("ji", "qi", "xue", "xi"),
    "深度学习": ("shen", "du", "xue", "xi"),
    "大数据": ("da", "shu", "ju"),
    "云计算": ("yun", "ji", "suan"),
    "区块链": ("qu", "kuai", "lian"),
    "虚拟现实": ("xu", "ni", "xian", "shi"),
    "增强现实": ("zeng", "qiang", "xian", "shi"),
    "物联网": ("wu", "lian", "wang"),
    "智慧城市": ("zhi", "hui", "cheng", "shi"),
    "电子商务": ("dian", "zi", "shang", "wu"),
    "移动支付": ("yi", "dong", "zhi", "fu"),
    "网上购物": ("wang", "shang", "gou", "wu"),
    "在线教育": ("zai", "xian", "jiao", "yu"),
    "远程办公": ("yuan", "cheng", "ban", "gong"),
    "共享经济": ("gong", "xiang", "jing", "ji"),
    "直播": ("zhi", "bo"),
    "短视频": ("duan", "shi", "pin"),
    "社交媒体": ("she", "jiao", "mei", "ti"),
    "微信": ("wei", "xin"),
    "微博": ("wei", "bo"),
    "抖音": ("dou", "yin"),
    "快手": ("kuai", "shou"),
    "B站": ("bi", "zhan"),
    "阿里巴巴": ("a", "li", "ba", "ba"),
    "腾讯": ("teng", "xun"),
    "百度": ("bai", "du"),
    "字节跳动": ("zi", "jie", "tiao", "dong"),
    "华为": ("hua", "wei"),
    "小米": ("xiao", "mi"),
    "苹果": ("ping", "guo"),
    "三星": ("san", "xing"),
    "电脑软件": ("dian", "nao", "ruan", "jian"),
    "操作系统": ("cao", "zuo", "xi", "tong"),
    "编程语言": ("bian", "cheng", "yu", "yan"),
    "软件开发": ("ruan", "jian", "kai", "fa"),
    "数据结构": ("shu", "ju", "jie", "gou"),
    "算法": ("suan", "fa"),
    "程序员": ("cheng", "xu", "yuan"),
    "产品经理": ("chan", "pin", "jing", "li"),
    "设计": ("she", "ji"),
    "用户体验": ("yong", "hu", "ti", "yan"),
    "界面": ("jie", "mian"),
    "美观": ("mei", "guan"),
    "简洁": ("jian", "jie"),
    "实用": ("shi", "yong"),
    "好看": ("hao", "kan"),
    "美味": ("mei", "wei"),
    "好吃": ("hao", "chi"),
    "好玩": ("hao", "wan"),
    "好听": ("hao", "ting"),
    "好看": ("hao", "kan"),
    "中国菜": ("zhong", "guo", "cai"),
    "川菜": ("chuan", "cai"),
    "粤菜": ("yue", "cai"),
    "粤菜": ("yue", "cai"),
    "湘菜": ("xiang", "cai"),
    "鲁菜": ("lu", "cai"),
    "苏菜": ("su", "cai"),
    "浙菜": ("zhe", "cai"),
    "闽菜": ("min", "cai"),
    "徽菜": ("hui", "cai"),
    "东北菜": ("dong", "bei", "cai"),
    "家常菜": ("jia", "chang", "cai"),
    "粤菜": ("yue", "cai"),
    "美食": ("mei", "shi"),
    "餐厅": ("can", "ting"),
    "饭店": ("fan", "dian"),
    "酒店": ("jiu", "dian"),
    "宾馆": ("bin", "guan"),
    "民宿": ("min", "su"),
    "旅游": ("lv", "you"),
    "景点": ("jing", "dian"),
    "门票": ("men", "piao"),
    "导游": ("dao", "you"),
    "纪念品": ("ji", "nian", "pin"),
    "北京": ("bei", "jing"),
    "上海": ("shang", "hai"),
    "广州": ("guang", "zhou"),
    "深圳": ("shen", "zhen"),
    "杭州": ("hang", "zhou"),
    "成都": ("cheng", "du"),
    "重庆": ("chong", "qing"),
    "武汉": ("wu", "han"),
    "西安": ("xi", "an"),
    "南京": ("nan", "jing"),
    "苏州": ("su", "zhou"),
    "长沙": ("chang", "sha"),
    "天津": ("tian", "jin"),
    "苏州": ("su", "zhou"),
    "厦门": ("xia", "men"),
    "青岛": ("qing", "dao"),
    "大连": ("da", "lian"),
    "无锡": ("wu", "xi"),
    "宁波": ("ning", "bo"),
    "中国首都": ("zhong", "guo", "shou", "du"),
    "亚洲": ("ya", "zhou"),
    "欧洲": ("ou", "zhou"),
    "美洲": ("mei", "zhou"),
    "非洲": ("fei", "zhou"),
    "大洋洲": ("da", "yang", "zhou"),
    "南极洲": ("nan", "ji", "zhou"),
    "太平洋": ("tai", "ping", "yang"),
    "大西洋": ("da", "xi", "yang"),
    "印度洋": ("yin", "du", "yang"),
    "北冰洋": ("bei", "bing", "yang"),
    "中国海": ("zhong", "guo", "hai"),
    "东中国海": ("dong", "zhong", "guo", "hai"),
    "南中国海": ("nan", "zhong", "guo", "hai"),
    "春节": ("chun", "jie"),
    "端午节": ("duan", "wu", "jie"),
    "中秋节": ("zhong", "qiu", "jie"),
    "国庆节": ("guo", "qing", "jie"),
    "劳动节": ("lao", "dong", "jie"),
    "元旦": ("yuan", "dan"),
    "元宵节": ("yuan", "xiao", "jie"),
    "清明节": ("qing", "ming", "jie"),
    "重阳节": ("chong", "yang", "jie"),
    "七夕节": ("qi", "xi", "jie"),
    "情人节": ("qing", "ren", "jie"),
    "圣诞节": ("sheng", "dan", "jie"),
    "新年": ("xin", "nian"),
    "除夕": ("chu", "xi"),
    "拜年": ("bai", "nian"),
    "红包": ("hong", "bao"),
    "烟花": ("yan", "hua"),
    "鞭炮": ("bian", "pao"),
    "春联": ("chun", "lian"),
    "福字": ("fu", "zi"),
    "饺子": ("jiao", "zi"),
    "汤圆": ("tang", "yuan"),
    "月饼": ("yue", "bing"),
    "粽子": ("zong", "zi"),
    "龙舟": ("long", "zhou"),
    "月亮": ("yue", "liang"),
    "太阳": ("tai", "yang"),
    "星星": ("xing", "xing"),
    "天空": ("tian", "kong"),
    "大地": ("da", "di"),
    "海洋": ("hai", "yang"),
    "山川": ("shan", "chuan"),
    "河流": ("he", "liu"),
    "森林": ("sen", "lin"),
    "沙漠": ("sha", "mo"),
    "草原": ("cao", "yuan"),
    "平原": ("ping", "yuan"),
    "高原": ("gao", "yuan"),
    "盆地": ("pen", "di"),
    "丘陵": ("qiu", "ling"),
    "地震": ("di", "zhen"),
    "火山": ("huo", "shan"),
    "台风": ("tai", "feng"),
    "洪水": ("hong", "shui"),
    "干旱": ("gan", "han"),
    "沙尘暴": ("sha", "chen", "bao"),
    "空气污染": ("kong", "qi", "wu", "ran"),
    "噪音": ("zao", "yin"),
    "白色垃圾": ("bai", "se", "la", "ji"),
    "碳排放": ("tan", "pai", "fang"),
    "清洁能源": ("qing", "jie", "neng", "yuan"),
    "太阳能": ("tai", "yang", "neng"),
    "风能": ("feng", "neng"),
    "水能": ("shui", "neng"),
    "核能": ("he", "neng"),
    "生物质能": ("sheng", "wu", "zhi", "neng"),
    "电动汽车": ("dian", "dong", "qi", "che"),
    "新能源": ("xin", "neng", "yuan"),
    "碳中和": ("tan", "zhong", "he"),
    "碳达峰": ("tan", "da", "feng"),
    "可持续发展": ("ke", "chi", "xu", "fa", "zhan"),
    "循环经济": ("xun", "huan", "jing", "ji"),
    "绿色出行": ("lv", "se", "chu", "xing"),
    "低碳生活": ("di", "tan", "sheng", "huo"),
    "垃圾分类": ("la", "ji", "fen", "lei"),
    "可回收": ("ke", "hui", "shou"),
    "厨余垃圾": ("chu", "yu", "la", "ji"),
    "有害垃圾": ("you", "hai", "la", "ji"),
    "其他垃圾": ("qi", "ta", "la", "ji"),
    "节约用水": ("jie", "yue", "yong", "shui"),
    "节约用电": ("jie", "yue", "yong", "dian"),
    "光盘行动": ("guang", "pan", "xing", "dong"),
    "减少塑料": ("jian", "shao", "su", "liao"),
    "保护动物": ("bao", "hu", "dong", "wu"),
    "野生动物": ("ye", "sheng", "dong", "wu"),
    "大熊猫": ("da", "xiong", "mao"),
    "金丝猴": ("jin", "si", "hou"),
    "朱鹮": ("zhu", "huan"),
    "丹顶鹤": ("dan", "ding", "he"),
    "扬子鳄": ("yang", "zi", "e"),
    "白鳍豚": ("bai", "qi", "tun"),
    "藏羚羊": ("zang", "ling", "yang"),
    "野牦牛": ("ye", "mao", "niu"),
    "雪豹": ("xue", "bao"),
    "中华鲟": ("zhong", "hua", "xun"),
    "金钱豹": ("jin", "qian", "bao"),
    "华南虎": ("hua", "nan", "hu"),
    "东北虎": ("dong", "bei", "hu"),
    "麋鹿": ("mi", "lu"),
    "小熊猫": ("xiao", "xiong", "mao"),
    "雪狼": ("xue", "lang"),
    "中华秋沙鸭": ("zhong", "hua", "qiu", "sha", "ya"),
    "金雕": ("jin", "diao"),
    "猎隼": ("lie", "sun"),
    "大鸨": ("da", "bao"),
    "遗鸥": ("yi", "ou"),
    "黑嘴鸥": ("hei", "zui", "ou"),
    "朱鹮": ("zhu", "huan"),
    "黑脸琵鹭": ("hei", "lian", "pi", "lu"),
    "丹顶鹤": ("dan", "ding", "he"),
    "东方白鹳": ("dong", "fang", "bai", "guan"),
    "黑鹳": ("hei", "guan"),
    "中华秋沙鸭": ("zhong", "hua", "qiu", "sha", "ya"),
    "褐马鸡": ("he", "ma", "ji"),
    "黄腹角雉": ("huang", "fu", "jiao", "zhi"),
    "蓝鹇": ("lan", "xian"),
    "黑颈鹤": ("hei", "jing", "he"),
    "白头鹤": ("bai", "tou", "he"),
    "白枕鹤": ("bai", "zhen", "he"),
    "灰鹤": ("hui", "he"),
    "沙丘鹤": ("sha", "qiu", "he"),
    "红顶鹤": ("hong", "ding", "he"),
    "白鹤": ("bai", "he"),
    "赤颈鹤": ("chi", "jing", "he"),
    "澳洲鹤": ("ao", "zhou", "he"),
    "肉垂鹤": ("rou", "chui", "he"),
    "蓝鹤": ("lan", "he"),
    "丹顶鹤": ("dan", "ding", "he"),
}
